table Customers
	lineageTag: dcff1c2d-530e-4cdd-8bfa-6df8276285f0

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: df0b59e6-94a1-45cc-82b3-2e8d935150c6
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_acct_num
		dataType: string
		lineageTag: a676cd5d-c3d9-42ca-b9ab-a2e30bc19a1c
		summarizeBy: none
		sourceColumn: customer_acct_num

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: cd1c249c-ff9c-47a7-8f6c-289d8d206402
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 89ad4ce1-29bd-4a08-b07e-bd2a48cb0171
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column customer_address
		dataType: string
		lineageTag: 6ada22fd-d2cc-43b2-b335-979ac32b76f3
		summarizeBy: none
		sourceColumn: customer_address

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 6c1e540d-7ff0-429f-82b9-ecbd699ea5ad
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state_province
		dataType: string
		lineageTag: 3f1e90db-d767-4a06-8beb-2dda2b0b6f10
		summarizeBy: none
		sourceColumn: customer_state_province

		annotation SummarizationSetBy = Automatic

	column customer_postal_code
		dataType: int64
		formatString: 0
		lineageTag: 338f9bd0-aae1-44ac-a060-869965998f5e
		summarizeBy: sum
		sourceColumn: customer_postal_code

		annotation SummarizationSetBy = Automatic

	column customer_country
		dataType: string
		lineageTag: 4477d54b-cf1b-4d45-a17c-4884da566b82
		summarizeBy: none
		sourceColumn: customer_country

		annotation SummarizationSetBy = Automatic

	column birthdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1a3e4b2f-9d0f-47c2-9bd7-7503c5e5d9a1
		summarizeBy: none
		sourceColumn: birthdate

		variation Variation
			isDefault
			relationship: 8820dbfa-431f-4859-9944-6d5f7fd023ec
			defaultHierarchy: LocalDateTable_d9116986-ccf2-45fe-80b1-55a1688212a5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column marital_status
		dataType: string
		lineageTag: 5b9f2b69-601e-45ef-b2f2-0e7aefb4b5dd
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

	column yearly_income
		dataType: string
		lineageTag: 6902c04d-a83f-49f5-9ad1-936dce5d3f48
		summarizeBy: none
		sourceColumn: yearly_income

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: d88a81f1-6041-4ca0-b33b-3e138e8fb304
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column total_children
		dataType: int64
		formatString: 0
		lineageTag: af868214-3d39-4113-b2bd-c637f9624c9e
		summarizeBy: sum
		sourceColumn: total_children

		annotation SummarizationSetBy = Automatic

	column num_children_at_home
		dataType: int64
		formatString: 0
		lineageTag: 83a5c07d-09a3-4d91-ad14-75744f37a06c
		summarizeBy: sum
		sourceColumn: num_children_at_home

		annotation SummarizationSetBy = Automatic

	column education
		dataType: string
		lineageTag: 0afcf771-6d82-4c50-8471-19837c4e0e49
		summarizeBy: none
		sourceColumn: education

		annotation SummarizationSetBy = Automatic

	column acct_open_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3b548e32-b076-4196-a1ff-f6b23a93ee3a
		summarizeBy: none
		sourceColumn: acct_open_date

		variation Variation
			isDefault
			relationship: 3c3a9e09-3213-4931-9cc0-cdae5a81eff0
			defaultHierarchy: LocalDateTable_c1a9a73a-baf1-4772-8742-d10d34973fd0.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column member_card
		dataType: string
		lineageTag: 2c7f4244-9ab3-4aa1-af73-5070b11f2e88
		summarizeBy: none
		sourceColumn: member_card

		annotation SummarizationSetBy = Automatic

	column occupation
		dataType: string
		lineageTag: a1686702-c4d0-44e8-aaa4-a219b0f9556f
		summarizeBy: none
		sourceColumn: occupation

		annotation SummarizationSetBy = Automatic

	column homeowner
		dataType: string
		lineageTag: db057381-5651-4a87-863b-9f21a288c16e
		summarizeBy: none
		sourceColumn: homeowner

		annotation SummarizationSetBy = Automatic

	column full_name
		dataType: string
		lineageTag: 7b2c4d00-3919-40a7-9a2c-dad296011129
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

	column birth_year
		dataType: string
		lineageTag: 9e89bab1-f6df-43ef-8f6a-5b3b91ec7fab
		summarizeBy: none
		sourceColumn: birth_year

		annotation SummarizationSetBy = Automatic

	column has_children
		dataType: string
		lineageTag: ce415fdd-3f9f-4dff-8138-af1893c5fb9f
		summarizeBy: none
		sourceColumn: has_children

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents("D:\Power BI\Maven Market\Maven+Market+CSV+Files\MavenMarket_Customers.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"customer_acct_num", type text}, {"first_name", type text}, {"last_name", type text}, {"customer_address", type text}, {"customer_city", type text}, {"customer_state_province", type text}, {"customer_postal_code", Int64.Type}, {"customer_country", type text}, {"birthdate", type text}, {"marital_status", type text}, {"yearly_income", type text}, {"gender", type text}, {"total_children", Int64.Type}, {"num_children_at_home", Int64.Type}, {"education", type text}, {"acct_open_date", type text}, {"member_card", type text}, {"occupation", type text}, {"homeowner", type text}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "Merged", each Text.Combine({[first_name], [last_name]}, " "), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Merged Column",{{"Merged", "full_name"}}),
				    #"Changes Date Format to USA" = Table.TransformColumnTypes(#"Renamed Columns", {{"birthdate", type date}}, "en-US"),
				    #"Added Birth Year Column" = Table.AddColumn(#"Changes Date Format to USA", "birth_year", each 
				Date.Year([birthdate])),
				    #"Added has_children Column" = Table.AddColumn(#"Added Birth Year Column", "has_children", each if [total_children] > 0 then "Y" else "N"),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Added has_children Column", {{"acct_open_date", type date}}, "en-US")
				in
				    #"Changed Type with Locale"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

